apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtual-service
spec:
  hosts:
  - my-service.example.com
  http:
  - name: my-http-route
    match:
    - uri:
        prefix: /v1
    rewrite:
      uri: /product/v1
    route:
    - destination:
        host: my-service
        port:
          number: 80
